apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: c66-add-remove-www
  namespace: #@ cloud66.app.namespace
spec:
  #@ if cloud66.app.middlewares.addRemoveWww.enabled:
  redirectRegex:
    regex: #@ cloud66.app.middlewares.addRemoveWww.regex
    replacement: #@ cloud66.app.middlewares.addRemoveWww.replacement
    permanent: #@ cloud66.app.middlewares.addRemoveWww.permanent
  #@ else:
  rateLimit:
    average: 0 # noop placeholder
  #@ end
