kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: traefik-c66-cluster-traefik
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: traefik-c66-cluster-traefik
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-c66-cluster-traefik
subjects:
- kind: ServiceAccount
  name: traefik
  namespace: c66-cluster-traefik
