kind: ServiceAccount
apiVersion: v1
metadata:
  name: traefik
  namespace: c66-cluster-traefik
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: traefik-c66-cluster-traefik
  annotations:
automountServiceAccountToken: false
