apiVersion: v1
data:
  AWS_ACCESS_KEY_ID: #@ base64.encode(cloud66.databaseService.backupAccessKeyId)
  AWS_SECRET_ACCESS_KEY: #@ base64.encode(cloud66.databaseService.backupSecretAccessKey)
kind: Secret
metadata:
  annotations:
    cloud66.com/databaseService: database-service-e9aa2f5c9d5210861a51ca54aa8b9df6 # important, keep this
  name: cloud66-backup-s3-credentials
  namespace: #@ cloud66.databaseService.namespace
type: Opaque
