#@ for user in cloud66.databaseService.users:
--- # keep
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  annotations:
    cloud66.com/databaseService: database-service-e9aa2f5c9d5210861a51ca54aa8b9df6 # important, keep this
  name: #@ user.passwordSecretName
  namespace: #@ cloud66.databaseService.namespace
data:
  username: #@ base64.encode(user.username)
  password: #@ base64.encode(user.password)
#@ end
