apiVersion: v1
kind: ServiceAccount
metadata:
  name: percona-pxc-operator
  namespace: c66-cluster-pxc
  annotations:
    cloud66.com/operator: operator-b58813e360581e222938f1007e8b1d18 # important, keep this
