#@ if cloud66.service.ports:
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud66.com/service: service-64d7e4e6905b3c28361a2cc50eac7c9a # important, keep this
  name: #@ cloud66.service.resourceName
  namespace: #@ cloud66.app.namespace
spec:
  selector:
    app: #@ cloud66.service.resourceName
  ports:
    #@ for/end port in cloud66.service.ports:
    - targetPort: #@ port.targetPort
      port: #@ port.port
      protocol: #@ port.protocol
      name: #@ port.name
#@ end
