apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: c66-headers-filter
  namespace: #@ cloud66.app.namespace
spec:
  plugin:
    headers-filter:
      enabled: #@ cloud66.app.middlewares.headersFilter.enabled
      debug: #@ cloud66.app.middlewares.headersFilter.debug
      allowMissingHeaders: #@ cloud66.app.middlewares.headersFilter.allowMissingHeaders
      allowList:
        #@ for/end header,values in struct.decode(cloud66.app.middlewares.headersFilter.allowList).items():
        (@= header @):
          #@ for/end value in values:
          - #@ value
      denyList:
        #@ for/end header,values in struct.decode(cloud66.app.middlewares.headersFilter.denyList).items():
        (@= header @):
          #@ for/end value in values:
          - #@ value
