apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: c66-ip-allow-list
  namespace: #@ cloud66.app.namespace
spec:
  #@ if cloud66.app.middlewares.ipAllowList.enabled:
  ipAllowList:
    sourceRange:
      #@ for/end ip in cloud66.app.middlewares.ipAllowList.ips:
      - #@ ip
  #@ else:
  rateLimit:
    average: 0 # noop placeholder
  #@ end
