apiVersion: v1
kind: Secret
type: Opaque
metadata:
  namespace: #@ cloud66.app.namespace
  name: c66-secrets
data:
  #@ for/end secret in cloud66.app.secrets:
  (@= secret.key @): (@= secret.value64 @)
