apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: c66-redirect-to-https
  namespace: #@ cloud66.app.namespace
spec:
  #@ if cloud66.app.middlewares.redirectToHttps.enabled:
  redirectScheme:
    scheme: https
    permanent: #@ cloud66.app.middlewares.redirectToHttps.permanent
  #@ else:
  rateLimit:
    average: 0 # noop placeholder
  #@ end
