#@ if cloud66.app.sslCertificates:
#@ for sslCertificate in dict(cloud66.app.sslCertificates).values():
--- # keep
apiVersion: v1
data:
  tls.crt: #@ base64.encode(sslCertificate.crt)
  tls.key: #@ base64.encode(sslCertificate.key)
kind: Secret
metadata:
  name: #@ sslCertificate.secretName
  namespace: #@ cloud66.app.namespace
type: kubernetes.io/tls
#@ end
#@ end
